# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_planner_control/DSM.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DSM(genpy.Message):
  _md5sum = "b450392d56d2a24eb5c7559f486528c5"
  _type = "franka_planner_control/DSM"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 time
float64 DSM
float64 tau
float64 dotq
float64 q
float64 dotp_EE
float64 terminalenergy
float64 sphere
float64 cylinder
float64 wall"""
  __slots__ = ['time','DSM','tau','dotq','q','dotp_EE','terminalenergy','sphere','cylinder','wall']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       time,DSM,tau,dotq,q,dotp_EE,terminalenergy,sphere,cylinder,wall

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DSM, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.time is None:
        self.time = 0.
      if self.DSM is None:
        self.DSM = 0.
      if self.tau is None:
        self.tau = 0.
      if self.dotq is None:
        self.dotq = 0.
      if self.q is None:
        self.q = 0.
      if self.dotp_EE is None:
        self.dotp_EE = 0.
      if self.terminalenergy is None:
        self.terminalenergy = 0.
      if self.sphere is None:
        self.sphere = 0.
      if self.cylinder is None:
        self.cylinder = 0.
      if self.wall is None:
        self.wall = 0.
    else:
      self.time = 0.
      self.DSM = 0.
      self.tau = 0.
      self.dotq = 0.
      self.q = 0.
      self.dotp_EE = 0.
      self.terminalenergy = 0.
      self.sphere = 0.
      self.cylinder = 0.
      self.wall = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.time, _x.DSM, _x.tau, _x.dotq, _x.q, _x.dotp_EE, _x.terminalenergy, _x.sphere, _x.cylinder, _x.wall))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.time, _x.DSM, _x.tau, _x.dotq, _x.q, _x.dotp_EE, _x.terminalenergy, _x.sphere, _x.cylinder, _x.wall,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10d().pack(_x.time, _x.DSM, _x.tau, _x.dotq, _x.q, _x.dotp_EE, _x.terminalenergy, _x.sphere, _x.cylinder, _x.wall))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 80
      (_x.time, _x.DSM, _x.tau, _x.dotq, _x.q, _x.dotp_EE, _x.terminalenergy, _x.sphere, _x.cylinder, _x.wall,) = _get_struct_10d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10d = None
def _get_struct_10d():
    global _struct_10d
    if _struct_10d is None:
        _struct_10d = struct.Struct("<10d")
    return _struct_10d
