panda: 

  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 30
    joint_names:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  arm_id: panda  

  arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      
    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0
      panda_joint1 :
        goal: 1.7
      panda_joint2 :
        goal: 1.7
      panda_joint3 :
        goal: 1.7
      panda_joint4 :
        goal: 1.7
      panda_joint5 :
        goal: 1.7
      panda_joint6 :
        goal: 1.7
      panda_joint7 :
        goal: 1.7
  
  
    gains: # Required because we're controlling an effort interface
      #panda_joint1 : {p: 12000.0, i: 0.0, d: 50, i_clamp: 10000}
      #panda_joint2 : {p: 30000, i: 0.02, d: 100, i_clamp: 10000}
      #panda_joint3 : {p: 18000.0, i: 0.01, d: 50, i_clamp: 1}
      #panda_joint4 : {p: 18000, i: 0.01, d: 70, i_clamp: 10000}
      #panda_joint5 : {p: 12000.0, i: 0.01, d: 70, i_clamp: 1}
      #panda_joint6 : {p: 7000, i: 0.01, d: 50, i_clamp: 1}
      #panda_joint7 : {p: 2000, i: 0.0, d: 20, i_clamp: 1}
      
      panda_joint1 : {p: 120.0, i: 0.0, d: 20.0, i_clamp: 2.5}
      panda_joint2 : {p: 300.0, i: 0.0, d: 20.0, i_clamp: 4.0}
      panda_joint3 : {p: 180.0, i: 0.0, d: 20.0, i_clamp: 2.5}
      panda_joint4 : {p: 180.0, i: 0.0, d: 20.0, i_clamp: 2.5}
      panda_joint5 : {p: 70.0, i: 0.0, d: 4.0, i_clamp: 1.0}
      panda_joint6 : {p: 20.0, i: 0.0, d: 3.0, i_clamp: 1.0}
      panda_joint7 : {p: 20.0, i: 0.0, d: 4.0, i_clamp: 1.0}


