# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from franka_planner_control/RobotEndEffectorPose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class RobotEndEffectorPose(genpy.Message):
  _md5sum = "08713e20671c442197b0728d63307e52"
  _type = "franka_planner_control/RobotEndEffectorPose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool rviz_orientation_problem
geometry_msgs/Pose xe_r

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['rviz_orientation_problem','xe_r']
  _slot_types = ['bool','geometry_msgs/Pose']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rviz_orientation_problem,xe_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotEndEffectorPose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.rviz_orientation_problem is None:
        self.rviz_orientation_problem = False
      if self.xe_r is None:
        self.xe_r = geometry_msgs.msg.Pose()
    else:
      self.rviz_orientation_problem = False
      self.xe_r = geometry_msgs.msg.Pose()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B7d().pack(_x.rviz_orientation_problem, _x.xe_r.position.x, _x.xe_r.position.y, _x.xe_r.position.z, _x.xe_r.orientation.x, _x.xe_r.orientation.y, _x.xe_r.orientation.z, _x.xe_r.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.xe_r is None:
        self.xe_r = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.rviz_orientation_problem, _x.xe_r.position.x, _x.xe_r.position.y, _x.xe_r.position.z, _x.xe_r.orientation.x, _x.xe_r.orientation.y, _x.xe_r.orientation.z, _x.xe_r.orientation.w,) = _get_struct_B7d().unpack(str[start:end])
      self.rviz_orientation_problem = bool(self.rviz_orientation_problem)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B7d().pack(_x.rviz_orientation_problem, _x.xe_r.position.x, _x.xe_r.position.y, _x.xe_r.position.z, _x.xe_r.orientation.x, _x.xe_r.orientation.y, _x.xe_r.orientation.z, _x.xe_r.orientation.w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.xe_r is None:
        self.xe_r = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 57
      (_x.rviz_orientation_problem, _x.xe_r.position.x, _x.xe_r.position.y, _x.xe_r.position.z, _x.xe_r.orientation.x, _x.xe_r.orientation.y, _x.xe_r.orientation.z, _x.xe_r.orientation.w,) = _get_struct_B7d().unpack(str[start:end])
      self.rviz_orientation_problem = bool(self.rviz_orientation_problem)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B7d = None
def _get_struct_B7d():
    global _struct_B7d
    if _struct_B7d is None:
        _struct_B7d = struct.Struct("<B7d")
    return _struct_B7d
