impedance_control_path_execute:
    type: franka_planner_control/ImpedanceControlPathExecute
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
    d_gains:
        - 50.0
        - 50.0
        - 50.0
        - 20.0
        - 20.0
        - 20.0
        - 10.0
    radius: 0.1
    acceleration_time: 2.0
    vel_max: 0.15
    publish_rate: 10.0
    coriolis_factor: 1.0

panda_model_controller:
    type: franka_planner_control/PandaModelController
    arm_id: panda

selector_erg_static_move_controller:
    type: franka_planner_control/SelectorErgStaticMoveController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp:
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 100.0 #60.0 #600.0
        - 50.0 #25.0 #250.0
        - 45.0 #15.0 #150.0
        - 15.0 #5.0 #50.0
    Kd:
        - 8.0 #5.0 #50.0
        - 8.0 #5.0 #50.0
        - 8.0 #50.0
        - 5.0 #2.0 #20.0
        - 2.0 #20.0
        - 2.0 #20.0
        - 1.0 #10.0 
    joint_friction_1:
        - 0.54615
        - 0.87224
        - 0.64068
        - 1.2794
        - 0.83904
        - 0.30301
        - 0.56489
    joint_friction_2:
        - 5.1181
        - 9.0657
        - 10.136
        - 5.5903
        - 8.3469
        - 17.133
        - 10.336
    joint_friction_3:
        - 0.039533
        - 0.025882
        - -0.046070
        - 0.036194
        - 0.026226
        - -0.021047
        - 0.0035526
    tau_limit:
        - 87.0 
        - 87.0
        - 87.0
        - 87.0
        - 12.0
        - 12.0 
        - 12.0 
    dotq_limit:
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.6100
        - 2.6100
        - 2.6100
    q_lowerlimit:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    q_upperlimit:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    dotp_EE_limit:
        - 1.7
        - 2.5
    pred_samples: 100
    pred_samplingtime: 0.002
    pred_interval: 0.0100
    eta: 0.05 
    zeta_q: 0.15 #0.2 #0.15
    kappa_q: 115.0   
    delta_q: 0.1
    kappa_tau: 9.0 
    delta_tau: 0.10
    kappa_dotq: 70.0 #50.0 #70.0 
    delta_dotq: 0.10
    kappa_dotp_EE: 70.0 #50.0 #70.0
    delta_dotp_EE: 0.01
    energy_limit: 12.0
    kappa_energy: 7.5  
    zeta_wall: 0.25
    kappa_wall: 100.0  
    delta_wall: 0.01 
    zeta_sphere: 0.4 
    kappa_sphere: 150.0    
    delta_sphere: 0.01 
    zeta_cylinder: 0.4 
    kappa_cylinder: 150.0    
    delta_cylinder: 0.01 #0.1 
    publish_rate: 1.0 #250.0

erg_static_move_controller:
    type: franka_planner_control/ErgStaticMoveController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp:
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 100.0 #60.0 #600.0
        - 50.0 #25.0 #250.0
        - 45.0 #15.0 #150.0
        - 15.0 #5.0 #50.0
    Kd:
        - 8.0 #5.0 #50.0
        - 8.0 #5.0 #50.0
        - 8.0 #50.0
        - 5.0 #2.0 #20.0
        - 2.0 #20.0
        - 2.0 #20.0
        - 1.0 #10.0 
    joint_friction_1:
        - 0.54615
        - 0.87224
        - 0.64068
        - 1.2794
        - 0.83904
        - 0.30301
        - 0.56489
    joint_friction_2:
        - 5.1181
        - 9.0657
        - 10.136
        - 5.5903
        - 8.3469
        - 17.133
        - 10.336
    joint_friction_3:
        - 0.039533
        - 0.025882
        - -0.046070
        - 0.036194
        - 0.026226
        - -0.021047
        - 0.0035526
    tau_limit:
        - 87.0 
        - 87.0
        - 87.0
        - 87.0
        - 12.0
        - 12.0 
        - 12.0 
    dotq_limit:
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.6100
        - 2.6100
        - 2.6100
    q_lowerlimit:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    q_upperlimit:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    dotp_EE_limit:
        - 1.7
        - 2.5
    pred_samples: 100
    pred_samplingtime: 0.002
    pred_interval: 0.0100
    eta: 0.05 #0.05 
    zeta_q: 0.15
    kappa_q: 115.0            #150.0 #75.0    #15.0     #  150.0 #100.0 #70.0 #150.0 #100.0 #75.0 #50.0 
    delta_q: 0.1 #0.10
    kappa_tau: 9.0             #12.0 #6.0   #1.2     #   12.0 #10.0 #7.0 #3.5 #12.0  #7.0 
    delta_tau: 0.10
    kappa_dotq: 70.0              #90.0 #45.0   #9.0    #  90.0 #60.0 #30.0 
    delta_dotq: 0.10
    kappa_dotp_EE: 70.0          #90.0 #45.0   #9.0    #   90.0 #60.0 #30.0
    delta_dotp_EE: 0.01
    zeta_sphere: 0.25 # 0.4 #0.2 #0.5
    kappa_sphere: 150.0   #30.0    #  300.0 #600.0 #300.0 #150.0 #50.0 #0.1 
    delta_sphere: 0.05 #0.01 #0.10 #0.05 #0.25 #0.10
    zeta_cylinder: 0.25 #0.4 #0.2 #0.4 #0.5
    kappa_cylinder: 150.0   #30.0   #  300.0 #100.0 #250.0 #230.0 #150.0 #75.0 #100.0 #150.0 #50.0 #0.1 
    delta_cylinder: 0.05 #0.01 #2 # 0.2 #0.05 #0.25 #0.10
    zeta_wall: 0.25 #0.1                  #0.25               #0.4 #0.2 #0.3
    kappa_wall: 100.0 #150.0                   #100.0              #30.0   #  300.0 #150.0 #300.0 #500.0 #300.0 #50.0 
    delta_wall: 0.01 #0.01 #0.1 #0.15
    energy_limit: 12.0 #tested this in obstacle free environment
    kappa_energy: 7.5          #10.0 #5.0   #1.0   #  10.0 #still to tune
    publish_rate: 1.0 #250.0

erg_dynamic_stay_controller:
    type: franka_planner_control/ErgDynamicStayController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp:
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 100.0 #60.0 #600.0
        - 50.0 #25.0 #250.0
        - 45.0 #15.0 #150.0
        - 15.0 #5.0 #50.0
    Kd:
        - 8.0 #5.0 #50.0
        - 8.0 #5.0 #50.0
        - 8.0 #50.0
        - 5.0 #2.0 #20.0
        - 2.0 #20.0
        - 2.0 #20.0
        - 1.0 #10.0 
    joint_friction_1:
        - 0.54615
        - 0.87224
        - 0.64068
        - 1.2794
        - 0.83904
        - 0.30301
        - 0.56489
    joint_friction_2:
        - 5.1181
        - 9.0657
        - 10.136
        - 5.5903
        - 8.3469
        - 17.133
        - 10.336
    joint_friction_3:
        - 0.039533
        - 0.025882
        - -0.046070
        - 0.036194
        - 0.026226
        - -0.021047
        - 0.0035526
    tau_limit:
        - 87.0 
        - 87.0
        - 87.0
        - 87.0
        - 12.0
        - 12.0 
        - 12.0 
    dotq_limit:
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.6100
        - 2.6100
        - 2.6100
    q_lowerlimit:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    q_upperlimit:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    dotp_EE_limit:
        - 1.7
        - 2.5
    pred_samples: 100
    pred_samplingtime: 0.002
    pred_interval: 0.0100
    eta: 0.05 #0.05 
    zeta_q: 0.15
    kappa_q: 115.0            #150.0 #75.0    #15.0     #  150.0 #100.0 #70.0 #150.0 #100.0 #75.0 #50.0 
    delta_q: 0.1 #0.10
    kappa_tau: 9.0             #12.0 #6.0   #1.2     #   12.0 #10.0 #7.0 #3.5 #12.0  #7.0 
    delta_tau: 0.10
    kappa_dotq: 70.0              #90.0 #45.0   #9.0    #  90.0 #60.0 #30.0 
    delta_dotq: 0.10
    kappa_dotp_EE: 70.0          #90.0 #45.0   #9.0    #   90.0 #60.0 #30.0
    delta_dotp_EE: 0.01
    zeta_sphere: 0.4 #0.25 # 0.4 #0.2 #0.5
    kappa_sphere: 175.0   #30.0    #  300.0 #600.0 #300.0 #150.0 #50.0 #0.1 
    delta_sphere: 0.01 #0.05 #0.01 #0.10 #0.05 #0.25 #0.10
    zeta_cylinder: 0.4 #0.25 #0.4 #0.2 #0.4 #0.5
    kappa_cylinder: 175.0   #30.0   #  300.0 #100.0 #250.0 #230.0 #150.0 #75.0 #100.0 #150.0 #50.0 #0.1 
    delta_cylinder: 0.01 #0.05 #0.01 #2 # 0.2 #0.05 #0.25 #0.10
    zeta_wall: 0.25 #0.1                  #0.25               #0.4 #0.2 #0.3
    kappa_wall: 100.0 #150.0                   #100.0              #30.0   #  300.0 #150.0 #300.0 #500.0 #300.0 #50.0 
    delta_wall: 0.01 #0.01 #0.1 #0.15
    energy_limit: 12.0 #tested this in obstacle free environment
    kappa_energy: 7.5          #10.0 #5.0   #1.0   #  10.0 #still to tune
    publish_rate: 1.0 #250.0

selector_erg_dynamic_move_controller:
    type: franka_planner_control/SelectorErgDynamicMoveController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp:
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 100.0 #60.0 #600.0
        - 50.0 #25.0 #250.0
        - 45.0 #15.0 #150.0
        - 15.0 #5.0 #50.0
    Kd:
        - 8.0 #5.0 #50.0
        - 8.0 #5.0 #50.0
        - 8.0 #50.0
        - 5.0 #2.0 #20.0
        - 2.0 #20.0
        - 2.0 #20.0
        - 1.0 #10.0 
    joint_friction_1:
        - 0.54615
        - 0.87224
        - 0.64068
        - 1.2794
        - 0.83904
        - 0.30301
        - 0.56489
    joint_friction_2:
        - 5.1181
        - 9.0657
        - 10.136
        - 5.5903
        - 8.3469
        - 17.133
        - 10.336
    joint_friction_3:
        - 0.039533
        - 0.025882
        - -0.046070
        - 0.036194
        - 0.026226
        - -0.021047
        - 0.0035526
    tau_limit:
        - 87.0 
        - 87.0
        - 87.0
        - 87.0
        - 12.0
        - 12.0 
        - 12.0 
    dotq_limit:
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.6100
        - 2.6100
        - 2.6100
    q_lowerlimit:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    q_upperlimit:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    dotp_EE_limit:
        - 1.7
        - 2.5
    pred_samples: 100
    pred_samplingtime: 0.002
    pred_interval: 0.0100
    eta: 0.05 #0.05 
    zeta_q: 0.15
    kappa_q: 115.0            #150.0 #75.0    #15.0     #  150.0 #100.0 #70.0 #150.0 #100.0 #75.0 #50.0 
    delta_q: 0.1 #0.10
    kappa_tau: 9.0             #12.0 #6.0   #1.2     #   12.0 #10.0 #7.0 #3.5 #12.0  #7.0 
    delta_tau: 0.10
    kappa_dotq: 70.0              #90.0 #45.0   #9.0    #  90.0 #60.0 #30.0 
    delta_dotq: 0.10
    kappa_dotp_EE: 70.0          #90.0 #45.0   #9.0    #   90.0 #60.0 #30.0
    delta_dotp_EE: 0.01
    zeta_sphere: 0.4 #0.4 #0.25 # 0.4 #0.2 #0.5
    kappa_sphere: 175.0 #150.0   #30.0    #  300.0 #600.0 #300.0 #150.0 #50.0 #0.1 
    delta_sphere: 0.01 #0.05 #0.01 #0.10 #0.05 #0.25 #0.10
    zeta_cylinder: 0.4 #0.4 #0.25 #0.4 #0.2 #0.4 #0.5rviz_visualization.addEndEffectorReferenceFrame(xe_r_,0,"end-effector reference pose"); erg_d
    kappa_cylinder: 175.0 #150.0   #30.0   #  300.0 #100.0 #250.0 #230.0 #150.0 #75.0 #100.0 #150.0 #50.0 #0.1 
    delta_cylinder: 0.01 #0.05 #0.01 #2 # 0.2 #0.05 #0.25 #0.10
    zeta_wall: 0.25 #0.1                  #0.25               #0.4 #0.2 #0.3
    kappa_wall: 100.0 #150.0                   #100.0              #30.0   #  300.0 #150.0 #300.0 #500.0 #300.0 #50.0 
    delta_wall: 0.01 #0.01 #0.1 #0.15
    energy_limit: 12.0 #tested this in obstacle free environment
    kappa_energy: 7.5          #10.0 #5.0   #1.0   #  10.0 #still to tune
    publish_rate: 1.0 #250.0

test_erg:
    type: franka_planner_control/TestErg
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp:
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 100.0 #60.0 #600.0
        - 50.0 #25.0 #250.0
        - 45.0 #15.0 #150.0
        - 15.0 #5.0 #50.0
    Kd:
        - 8.0 #5.0 #50.0
        - 8.0 #5.0 #50.0
        - 8.0 #50.0
        - 5.0 #2.0 #20.0
        - 2.0 #20.0
        - 2.0 #20.0
        - 1.0 #10.0 
    joint_friction_1:
        - 0.54615
        - 0.87224
        - 0.64068
        - 1.2794
        - 0.83904
        - 0.30301
        - 0.56489
    joint_friction_2:
        - 5.1181
        - 9.0657
        - 10.136
        - 5.5903
        - 8.3469
        - 17.133
        - 10.336
    joint_friction_3:
        - 0.039533
        - 0.025882
        - -0.046070
        - 0.036194
        - 0.026226
        - -0.021047
        - 0.0035526
    tau_limit:
        - 87.0 
        - 87.0
        - 87.0
        - 87.0
        - 12.0
        - 12.0 
        - 12.0 
    dotq_limit:
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.6100
        - 2.6100
        - 2.6100
    q_lowerlimit:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    q_upperlimit:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    dotp_EE_limit:
        - 1.7
        - 2.5
    pred_samples: 100
    pred_samplingtime: 0.002
    pred_interval: 0.0100
    eta: 0.05 
    zeta_q: 0.15
    kappa_q: 115.0   
    delta_q: 0.1
    kappa_tau: 9.0 
    delta_tau: 0.10
    kappa_dotq: 70.0 
    delta_dotq: 0.10
    kappa_dotp_EE: 70.0
    delta_dotp_EE: 0.01
    energy_limit: 12.0
    kappa_energy: 7.5  
    zeta_wall: 0.25
    kappa_wall: 100.0  
    delta_wall: 0.01 
    zeta_sphere: 0.4 
    kappa_sphere: 150.0    
    delta_sphere: 0.01 
    zeta_cylinder: 0.4 
    kappa_cylinder: 150.0    
    delta_cylinder: 0.1 #0.01 
    publish_rate: 1.0 #250.0

test_erg_selector:
    type: franka_planner_control/TestErgSelector
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp:
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 120.0 #60.0 #600.0
        - 100.0 #60.0 #600.0
        - 50.0 #25.0 #250.0
        - 45.0 #15.0 #150.0
        - 15.0 #5.0 #50.0
    Kd:
        - 8.0 #5.0 #50.0
        - 8.0 #5.0 #50.0
        - 8.0 #50.0
        - 5.0 #2.0 #20.0
        - 2.0 #20.0
        - 2.0 #20.0
        - 1.0 #10.0 
    joint_friction_1:
        - 0.54615
        - 0.87224
        - 0.64068
        - 1.2794
        - 0.83904
        - 0.30301
        - 0.56489
    joint_friction_2:
        - 5.1181
        - 9.0657
        - 10.136
        - 5.5903
        - 8.3469
        - 17.133
        - 10.336
    joint_friction_3:
        - 0.039533
        - 0.025882
        - -0.046070
        - 0.036194
        - 0.026226
        - -0.021047
        - 0.0035526
    tau_limit:
        - 87.0 
        - 87.0
        - 87.0
        - 87.0
        - 12.0
        - 12.0 
        - 12.0 
    dotq_limit:
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.1750
        - 2.6100
        - 2.6100
        - 2.6100
    q_lowerlimit:
        - -2.8973
        - -1.7628
        - -2.8973
        - -3.0718
        - -2.8973
        - -0.0175
        - -2.8973
    q_upperlimit:
        - 2.8973
        - 1.7628
        - 2.8973
        - -0.0698
        - 2.8973
        - 3.7525
        - 2.8973
    dotp_EE_limit:
        - 1.7
        - 2.5
    pred_samples: 100
    pred_samplingtime: 0.002
    pred_interval: 0.0100
    eta: 0.05 
    zeta_q: 0.15 #0.2 #0.15
    kappa_q: 115.0   
    delta_q: 0.1
    kappa_tau: 9.0 
    delta_tau: 0.10
    kappa_dotq: 70.0 #50.0 #70.0 
    delta_dotq: 0.10
    kappa_dotp_EE: 70.0 #50.0 #70.0
    delta_dotp_EE: 0.01
    energy_limit: 12.0
    kappa_energy: 7.5  
    zeta_wall: 0.25
    kappa_wall: 100.0  
    delta_wall: 0.01 
    zeta_sphere: 0.4 
    kappa_sphere: 150.0    
    delta_sphere: 0.01 
    zeta_cylinder: 0.4 
    kappa_cylinder: 150.0    
    delta_cylinder: 0.01 #0.1 
    publish_rate: 1.0 #250.0